%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1080
image_height: 1920
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 1.963296e+03
   fy:1.963296e+03
   cx: 6.430000e+02
   cy: 3.580000e+02
