# This message holds a collection of informaton related to
# find_connection call in loop fusion module.

string matched_file_name
geometry_msgs/Pose rel_pose
time cur_time
time old_time
sensor_msgs/Image cur_image
sensor_msgs/Image old_image
loop_fusion/PointUV[] step0_cur_ponits
loop_fusion/PointUV[] step0_old_ponits
loop_fusion/PointUV[] step1_cur_ponits
loop_fusion/PointUV[] step1_old_ponits
loop_fusion/PointUV[] step3_cur_ponits
loop_fusion/PointUV[] step3_old_ponits
